name: biotoolkits
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.7.1
  - pandas=1.0.5
  - matplotlib=3.2.2
  - gatk4=4.1.8.1
  - cromwell=52
  - fastp=0.20.0
  - samtools=1.10
  - bedtools=2.29.2
  - bcftools=1.10
  - seqkit=0.13.2
  - seqtk=1.3
  - qualimap=2.2.2d
  - cnvkit=0.9.7
  - pigz>=2.4
  - openpyxl=3.0.3
  - pymysql=0.9.3
  - xlwt=1.3.0
  - xlrd=1.2.0
