name: cnvtools
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - numpy=1.19.2
  - scipy=1.5.2
  - pandas=1.1.3
  - matplotlib=3.3.2
  - pip=20.2.3
  - setuptools=50.3.0
  - wheel=0.34.2
  - twine=3.2.0
  - pytest=6.1.1
  - fastp=0.20.0
  - samtools=1.10
  - bedtools=2.29.2
  - bcftools=1.10
  - cnvkit=0.9.7
  - pigz>=2.4
  - openpyxl=3.0.3
  - pymysql=0.9.3
  - xlwt=1.3.0
  - xlrd=1.2.0
  - reportlab=3.5.45
  - statsmodels=0.11.1
  - requests
